# Generated by Django 3.0.6 on 2020-05-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='name',
            field=models.CharField(default='Name', max_length=50),
            preserve_default=False,
        ),
    ]
