# Generated by Django 3.0.6 on 2020-05-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_feed_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='feed',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
