# Generated by Django 3.0.6 on 2020-05-31 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200531_1308'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feed',
        ),
    ]
