# Generated by Django 3.0.6 on 2020-06-02 14:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_delete_feed'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebProxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('site_url', models.CharField(blank=True, max_length=255, null=True)),
                ('feed_url', models.CharField(max_length=255)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_polled', models.DateTimeField(blank=True, max_length=255, null=True)),
                ('due_poll', models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0))),
                ('etag', models.CharField(blank=True, max_length=255, null=True)),
                ('last_modified', models.CharField(blank=True, max_length=255, null=True)),
                ('last_result', models.CharField(blank=True, max_length=255, null=True)),
                ('interval', models.PositiveIntegerField(default=400)),
                ('last_success', models.DateTimeField(null=True)),
                ('last_change', models.DateTimeField(null=True)),
                ('live', models.BooleanField(default=True)),
                ('status_code', models.PositiveIntegerField(default=0)),
                ('last_302_url', models.CharField(blank=True, max_length=255, null=True)),
                ('last_302_start', models.DateTimeField(blank=True, null=True)),
                ('max_index', models.IntegerField(default=0)),
                ('num_subs', models.IntegerField(default=1)),
                ('is_cloudflare', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('body', models.TextField()),
                ('link', models.CharField(blank=True, max_length=512, null=True)),
                ('found', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(db_index=True)),
                ('guid', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('index', models.IntegerField(db_index=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main.Source')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Enclosure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(default=0)),
                ('href', models.CharField(max_length=512)),
                ('type', models.CharField(max_length=256)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enclosures', to='main.Post')),
            ],
        ),
    ]
