# Generated by Django 3.0.6 on 2020-06-04 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_lastchecked_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enclosure',
        ),
    ]
